name: lint

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  Explore-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
        env:
          GO111MODULE: on

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
