name: Go GitHub Actions 

on: 
  push:
      branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  Explore-Packge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.2.0

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: '-l -d'
       
      - name: Test
        run: go test -v ./...
  

